import { formChoices } from './form-choices';
import { ActionFieldBehavior } from './action-form-behavior';
import type { ValueChoice } from './action-value-editor';
import { scalarText } from '../../shared/scalar-text';
import type { WorkflowInputField, WorkflowInputType } from '../../shared/workflow-contract';
import type { WorkspaceProperty } from '../../shared/property-contract';
import type { Locale } from '../app/i18n';
import { Select } from '../ui/select';
import { inputKey } from './input-defaults';
export function ActionInputsEditor({ fields, onChange, databases, schemas, locale, child = false, outerChoices = [] }: { fields: readonly WorkflowInputField[]; onChange: (fields: readonly WorkflowInputField[]) => void; databases: readonly { id: string; title: string }[]; schemas: Record<string, readonly WorkspaceProperty[]>; locale: Locale; child?: boolean; outerChoices?: ValueChoice[] }) {
  const ar = locale === 'ar'; const types: WorkflowInputType[] = ['text', 'number', 'boolean', 'date', 'datetime', 'select', 'record', ...(!child ? ['collection' as const] : [])];
  const choices = [...outerChoices, ...formChoices(fields, schemas, child)];
  const patch = (index: number, change: Partial<WorkflowInputField>) => onChange(fields.map((f, i) => index === i ? { ...f, ...change } : f));
  return <>{fields.map((field, index) => <div className="action-input-row" key={field.id ?? inputKey(field, index)}>
    <div className="action-row"><input aria-label="Input name" placeholder={ar ? 'اسم المدخل' : 'Input name'} value={field.label} onChange={e => patch(index, { label: e.target.value })}/><Select aria-label="Input type" value={field.type} onChange={e => { const type = e.target.value as WorkflowInputType; patch(index, { type, fields: type === 'collection' ? [] : undefined, prefill: undefined, derived: undefined, pickerFilter: undefined, displayPropertyIds: undefined, allowCreate: undefined, defaultValue: undefined }); }}>{types.map(type => <option key={type} value={type}>{type === 'collection' ? (ar ? 'صفوف متكررة' : 'Repeated rows') : ({ text: 'Text', string: 'Text', number: 'Number', boolean: 'Boolean', date: 'Date', datetime: 'Date and time', select: 'Select', record: 'Record', collection: 'Repeated rows' })[type]}</option>)}</Select><label><input type="checkbox" checked={!!field.required} onChange={e => patch(index, { required: e.target.checked })}/>{ar ? 'مطلوب' : 'Required'}</label><button type="button" aria-label="Remove input" onClick={() => onChange(fields.filter((_, i) => i !== index))}>×</button></div>
    {field.type === 'record' && <Select aria-label="Record database" value={field.databaseId ?? ''} onChange={e => patch(index, { databaseId: e.target.value, pickerFilter: undefined, displayPropertyIds: undefined })}><option value="">{ar ? 'قاعدة البيانات' : 'Choose database'}</option>{databases.map(db => <option key={db.id} value={db.id}>{db.title}</option>)}</Select>}
    {field.type === 'select' && <label>{ar ? 'الخيارات' : 'Options (comma separated)'}<input value={field.options?.map(o => o.label).join(', ') ?? ''} onChange={e => patch(index, { options: e.target.value.split(',').map((label, i) => ({ label: label.trim(), value: field.options?.[i]?.value ?? crypto.randomUUID() })) })}/></label>}
    {field.type === 'collection' ? <><div className="action-row"><label>{ar ? 'أقل عدد' : 'Minimum rows'}<input type="number" min={0} max={100} value={field.minItems ?? 0} onChange={e => patch(index, { minItems: Number(e.target.value) })}/></label><label>{ar ? 'أقصى عدد' : 'Maximum rows'}<input type="number" min={0} max={100} value={field.maxItems ?? 100} onChange={e => patch(index, { maxItems: Number(e.target.value) })}/></label></div><ActionInputsEditor fields={field.fields ?? []} onChange={next => patch(index, { fields: next })} databases={databases} schemas={schemas} locale={locale} child outerChoices={choices}/></> : <>
      <label>{ar ? 'قيمة افتراضية' : 'Default'}{field.type === 'boolean' ? <input type="checkbox" checked={field.defaultValue === true} onChange={e => patch(index, { defaultValue: e.target.checked })}/> : <input type={field.type === 'number' ? 'number' : field.type === 'date' ? 'date' : field.type === 'datetime' ? 'datetime-local' : 'text'} step="any" value={scalarText(field.defaultValue ?? '')} onChange={e => patch(index, { defaultValue: field.type === 'number' && e.target.value !== '' ? Number(e.target.value) : e.target.value || undefined })}/>}</label>
      <label hidden={!!field.derived}>{ar ? 'تعبئة من سجل محدد' : 'Prefill from selected record'}<Select aria-label="Prefill property" value={field.prefill ? JSON.stringify(field.prefill) : ''} onChange={e => patch(index, { prefill: e.target.value ? JSON.parse(e.target.value) as WorkflowInputField['prefill'] : undefined })}><option value="">{ar ? 'بدون' : 'None'}</option>{fields.slice(0, index).filter(f => f.type === 'record').flatMap(source => (schemas[source.databaseId ?? ''] ?? []).filter(p => !['relation', 'file', 'button'].includes(p.type)).map(p => { const value = { inputKey: inputKey(source, fields.indexOf(source)), databaseId: source.databaseId!, propertyId: p.id }; return <option key={JSON.stringify(value)} value={JSON.stringify(value)}>{source.label} · {p.name}</option>; }))}</Select></label>
    </>}
    <ActionFieldBehavior field={field} onChange={change => patch(index, change)} choices={choices} properties={schemas[field.databaseId ?? ''] ?? []} locale={locale}/>
  </div>)}<button type="button" onClick={() => { const id = crypto.randomUUID(); onChange([...fields, { id, key: id, label: '', type: 'text' }]); }}>{ar ? '+ مدخل' : '+ Input'}</button></>;
}
