import { formChoices } from './form-choices';
import type { WorkflowInputField, WorkflowInputSchema, WorkflowValue } from '../../shared/workflow-contract';
import type { WorkspaceProperty } from '../../shared/property-contract';
import type { FilterNode, FilterOperator } from '../../shared/query-contract';
import type { Locale } from '../app/i18n';
import { ActionValueEditor, type ValueChoice } from './action-value-editor';
import { Select } from '../ui/select';
import { inputKey } from './input-defaults';
const fixed = (value: unknown): WorkflowValue => ({ source: 'literal', value });
function PickerFilterEditor({ filter, onChange, properties, choices, locale }: { filter: FilterNode; onChange: (filter: FilterNode) => void; properties: readonly WorkspaceProperty[]; choices: ValueChoice[]; locale: Locale }) {
  if (filter.kind === 'relation') return <p>Relation filters are not supported in record inputs.</p>;
  if (filter.kind === 'group') return <div className="action-filter-group"><Select aria-label="Match conditions" value={filter.operator} onChange={e => onChange({ ...filter, operator: e.target.value as 'AND' | 'OR' })}><option value="AND">{locale === 'ar' ? 'كل الشروط' : 'All conditions'}</option><option value="OR">{locale === 'ar' ? 'أي شرط' : 'Any condition'}</option></Select>{filter.conditions.map((node, i) => <div key={i} className="action-row"><PickerFilterEditor filter={node} onChange={next => onChange({ ...filter, conditions: filter.conditions.map((v, j) => i === j ? next : v) })} properties={properties} choices={choices} locale={locale}/><button type="button" aria-label="Remove picker condition" onClick={() => onChange({ ...filter, conditions: filter.conditions.filter((_, j) => i !== j) })}>×</button></div>)}<button type="button" onClick={() => onChange({ ...filter, conditions: [...filter.conditions, { kind: 'property', propertyId: properties[0]?.id ?? '', operator: 'equals', value: fixed('') }] })}>{locale === 'ar' ? '+ شرط' : '+ Condition'}</button></div>;
  return <div className="action-row"><Select aria-label="Picker property" value={filter.propertyId} onChange={e => onChange({ ...filter, propertyId: e.target.value })}>{properties.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</Select><Select aria-label="Picker comparison" value={filter.operator} onChange={e => onChange({ ...filter, operator: e.target.value as FilterOperator })}>{['equals', 'not_equals', 'greater_than', 'greater_than_or_equal', 'less_than', 'less_than_or_equal', 'contains', 'is_empty', 'is_not_empty', 'is_checked', 'is_not_checked'].map((op, i) => <option key={op} value={op}>{['=', '≠', '>', '≥', '<', '≤', 'Contains', 'Is empty', 'Is not empty', 'Is checked', 'Is not checked'][i]}</option>)}</Select>{!['is_empty', 'is_not_empty', 'is_checked', 'is_not_checked'].includes(filter.operator) && <ActionValueEditor value={filter.value && typeof filter.value === 'object' && 'source' in filter.value ? filter.value : fixed(filter.value ?? '')} onChange={value => onChange({ ...filter, value })} choices={choices} locale={locale}/>}</div>;
}
export function ActionFieldBehavior({ field, onChange, choices, properties, locale }: { field: WorkflowInputField; onChange: (patch: Partial<WorkflowInputField>) => void; choices: ValueChoice[]; properties: readonly WorkspaceProperty[]; locale: Locale }) {
  const ar = locale === 'ar';
  return <details className="action-behavior"><summary>{ar ? 'الحساب والشروط' : 'Calculation & conditions'}</summary>{field.type !== 'collection' && <><label><input type="checkbox" checked={!!field.derived} onChange={e => onChange({ derived: e.target.checked ? { value: fixed(0), allowOverride: true } : undefined, prefill: undefined })}/>{ar ? 'قيمة محسوبة مباشرة' : 'Calculate live'}</label>{field.derived && <><ActionValueEditor locale={locale} value={field.derived.value} choices={choices} onChange={value => onChange({ derived: { ...field.derived!, value } })}/><label><input type="checkbox" checked={!!field.derived.allowOverride} onChange={e => onChange({ derived: { ...field.derived!, allowOverride: e.target.checked } })}/>{ar ? 'السماح بالتعديل' : 'Allow manual override'}</label></>}</>}{(['visibleWhen', 'requiredWhen', 'disabledWhen'] as const).map((key, i) => <div key={key}><label><input type="checkbox" checked={!!field[key]} onChange={e => onChange({ [key]: e.target.checked ? fixed(true) : undefined })}/>{(ar ? ['يظهر عندما', 'مطلوب عندما', 'معطل عندما'] : ['Visible when', 'Required when', 'Disabled when'])[i]}</label>{field[key] && <ActionValueEditor locale={locale} value={field[key]} choices={choices} onChange={value => onChange({ [key]: value })}/>}</div>)}{field.type === 'record' && <><label><input type="checkbox" checked={!!field.allowCreate} onChange={e => onChange({ allowCreate: e.target.checked })}/>{ar ? 'السماح بإنشاء سجل' : 'Allow adding records'}</label><label><input type="checkbox" checked={!!field.pickerFilter} onChange={e => onChange({ pickerFilter: e.target.checked ? { kind: 'group', operator: 'AND', conditions: [] } : undefined })}/>{ar ? 'تصفية السجلات' : 'Filter records'}</label>{field.pickerFilter && <PickerFilterEditor filter={field.pickerFilter} onChange={pickerFilter => onChange({ pickerFilter })} properties={properties} choices={choices} locale={locale}/>}<div><span>{ar ? 'تفاصيل السجل (حتى ٣)' : 'Record details (up to 3)'}</span>{properties.map(p => <label key={p.id}><input type="checkbox" checked={field.displayPropertyIds?.includes(p.id) ?? false} disabled={!field.displayPropertyIds?.includes(p.id) && (field.displayPropertyIds?.length ?? 0) >= 3} onChange={e => onChange({ displayPropertyIds: e.target.checked ? [...(field.displayPropertyIds ?? []), p.id] : field.displayPropertyIds?.filter(id => id !== p.id) })}/>{p.name}</label>)}</div></>}</details>;
}
export function ActionFormBehavior({ schema, onChange, choices, schemas, locale }: { schema: WorkflowInputSchema; onChange: (schema: WorkflowInputSchema) => void; choices: ValueChoice[]; schemas: Record<string, readonly WorkspaceProperty[]>; locale: Locale }) {
  const ar = locale === 'ar';
  return <details className="action-behavior"><summary>{ar ? 'رسائل ومعاينة' : 'Messages & preview'}</summary>{(schema.rules ?? []).map((rule, i) => {
    const patch = (change: Partial<typeof rule>) => onChange({ ...schema, rules: schema.rules!.map((r, j) => i === j ? { ...r, ...change } : r) });
    const collection = rule.collection?.source === 'variable' ? schema.fields.find(f => inputKey(f, schema.fields.indexOf(f)) === (rule.collection as { key: string }).key) : undefined;
    return <div className="action-step" key={rule.id}><div className="action-row"><Select aria-label="Message severity" value={rule.severity} onChange={e => patch({ severity: e.target.value as typeof rule.severity })}><option value="INFO">{ar ? 'معلومة' : 'Information'}</option><option value="WARNING">{ar ? 'تحذير · يتطلب تأكيداً' : 'Warning · confirmation'}</option><option value="BLOCK">{ar ? 'منع التنفيذ' : 'Block submission'}</option></Select><button type="button" aria-label="Remove rule" onClick={() => onChange({ ...schema, rules: schema.rules?.filter((_, j) => i !== j) })}>×</button></div><input aria-label="Message" placeholder={ar ? 'الرسالة' : 'Message'} value={rule.message} onChange={e => patch({ message: e.target.value })}/><Select aria-label="Rule scope" value={collection ? inputKey(collection, schema.fields.indexOf(collection)) : ''} onChange={e => patch({ collection: e.target.value ? { source: 'variable', key: e.target.value } : undefined })}><option value="">{ar ? 'الإجراء' : 'Whole action'}</option>{schema.fields.filter(f => f.type === 'collection').map(f => <option key={f.key ?? f.id} value={inputKey(f, schema.fields.indexOf(f))}>{f.label} · {ar ? 'كل صف' : 'Each row'}</option>)}</Select><ActionValueEditor locale={locale} choices={[...choices, ...formChoices(collection?.fields ?? [], schemas, true)]} value={rule.condition} onChange={condition => patch({ condition })}/></div>;
  })}<button type="button" onClick={() => onChange({ ...schema, rules: [...(schema.rules ?? []), { id: crypto.randomUUID(), severity: 'WARNING', message: '', condition: fixed(false) }] })}>{ar ? '+ رسالة شرطية' : '+ Conditional message'}</button><h4>{ar ? 'المعاينة' : 'Live summary'}</h4>{(schema.summary ?? []).map((item, i) => <div className="action-row" key={i}><input aria-label="Summary label" value={item.label} onChange={e => onChange({ ...schema, summary: schema.summary!.map((s, j) => i === j ? { ...s, label: e.target.value } : s) })}/><ActionValueEditor locale={locale} choices={choices} value={item.value} onChange={value => onChange({ ...schema, summary: schema.summary!.map((s, j) => i === j ? { ...s, value } : s) })}/><button type="button" aria-label="Remove summary item" onClick={() => onChange({ ...schema, summary: schema.summary?.filter((_, j) => i !== j) })}>×</button></div>)}<button type="button" onClick={() => onChange({ ...schema, summary: [...(schema.summary ?? []), { label: '', value: fixed(0) }] })}>{ar ? '+ قيمة في المعاينة' : '+ Preview value'}</button></details>;
}
