// Historical v0.2 conversion data. Never exposed as a product template.
import type { WorkspaceTemplateV2 } from '../../shared/template-v2-contract';
export function legacyRetailMigrationTemplate(locale: 'ar' | 'en' = 'en'): WorkspaceTemplateV2 {
    const isAr = locale === 'ar';

    return {
      author: 'Max OS',
      databases: [
        {
          key: 'db_products',
          properties: [
            { key: 'prop_prod_name', name: isAr ? 'اسم المنتج' : 'Name', required: true, type: 'title' },
            { key: 'prop_prod_sku', name: isAr ? 'الباركود / SKU' : 'SKU', type: 'text', uniqueValue: true },
            { key: 'prop_prod_brand', name: isAr ? 'الماركة' : 'Brand', type: 'text' },
            { key: 'prop_prod_model', name: isAr ? 'الموديل' : 'Model', type: 'text' },
            { key: 'prop_prod_imei', name: isAr ? 'IMEI / الرقم التسلسلي' : 'IMEI / Serial', type: 'text', uniqueValue: true },
            {
              key: 'prop_prod_condition',
              name: isAr ? 'الحالة' : 'Condition',
              options: [{ label: isAr ? 'جديد' : 'New' }, { label: isAr ? 'مستعمل' : 'Used' }, { label: isAr ? 'مجدّد' : 'Refurbished' }],
              type: 'select',
            },
            {
              key: 'prop_prod_category',
              name: isAr ? 'التصنيف' : 'Category',
              options: [
                { label: isAr ? 'هواتف' : 'Phones' },
                { label: isAr ? 'إكسسوارات' : 'Accessories' },
                { label: isAr ? 'صيانة' : 'Repairs' },
              ],
              type: 'select',
            },
            { key: 'prop_prod_cost', name: isAr ? 'سعر التكلفة' : 'Cost Price', type: 'number' },
            { key: 'prop_prod_price', name: isAr ? 'سعر البيع' : 'Selling Price', type: 'number' },
            {
              config: {
                rollup: {
                  aggregation: 'sum',
                  relationPropertyId: 'prop_prod_inv_rel',
                  targetPropertyId: 'prop_inv_delta',
                },
              },
              key: 'prop_prod_stock',
              name: isAr ? 'المخزون المتوفر' : 'Stock',
              type: 'rollup',
            },
            {
              config: { relationId: 'rel_prod_inv' },
              key: 'prop_prod_inv_rel',
              name: isAr ? 'حركات المخزون' : 'Inventory Movements',
              type: 'relation',
            },
            { key: 'prop_prod_active', name: isAr ? 'نشط' : 'Active', type: 'checkbox' },
          ],
          title: isAr ? 'المنتجات' : 'Products',
          views: [
            { key: 'view_products_all', layout: 'table', name: isAr ? 'كل الأصناف' : 'All Items', propertyKeys: ['prop_prod_name', 'prop_prod_brand', 'prop_prod_model', 'prop_prod_imei', 'prop_prod_cost', 'prop_prod_price', 'prop_prod_stock'], sorts: [{ direction: 'asc', propertyId: 'prop_prod_name' }] },
          ],
          visibility: 'normal',
        },
        {
          key: 'db_people',
          properties: [
            { key: 'prop_people_name', name: isAr ? 'الاسم' : 'Name', required: true, type: 'title' },
            {
              key: 'prop_people_type',
              name: isAr ? 'النوع' : 'Type',
              options: [
                { label: isAr ? 'عميل' : 'Customer' },
                { label: isAr ? 'مورد' : 'Supplier' },
              ],
              type: 'select',
            },
            { key: 'prop_people_phone', name: isAr ? 'الهاتف' : 'Phone', type: 'phone' },
            {
              config: {
                rollup: {
                  aggregation: 'sum',
                  relationPropertyId: 'prop_people_money_rel',
                  targetPropertyId: 'prop_mm_amount',
                },
              },
              key: 'prop_people_balance',
              name: isAr ? 'الرصيد' : 'Balance',
              type: 'rollup',
            },
            {
              config: { relationId: 'rel_people_money' },
              key: 'prop_people_money_rel',
              name: isAr ? 'حركات الأموال' : 'Money Movements',
              type: 'relation',
            },
          ],
          title: isAr ? 'جهات التعامل' : 'People',
          views: [{ key: 'view_people_all', layout: 'table', name: isAr ? 'العملاء والموردون' : 'Customers & Suppliers', propertyKeys: ['prop_people_name', 'prop_people_type', 'prop_people_phone', 'prop_people_balance'], sorts: [{ direction: 'asc', propertyId: 'prop_people_name' }] }],
          visibility: 'normal',
        },
        {
          key: 'db_accounts',
          properties: [
            { key: 'prop_acc_name', name: isAr ? 'اسم الحساب' : 'Name', required: true, type: 'title' },
            {
              key: 'prop_acc_type',
              name: isAr ? 'النوع' : 'Type',
              options: [
                { label: isAr ? 'خزينة نقدية' : 'Cash' },
                { label: isAr ? 'حساب بنكي' : 'Bank' },
                { label: isAr ? 'محفظة إلكترونية' : 'Digital Wallet' },
              ],
              type: 'select',
            },
            {
              config: {
                rollup: {
                  aggregation: 'sum',
                  relationPropertyId: 'prop_acc_money_rel',
                  targetPropertyId: 'prop_mm_amount',
                },
              },
              key: 'prop_acc_balance',
              name: isAr ? 'الرصيد' : 'Balance',
              type: 'rollup',
            },
            {
              config: { relationId: 'rel_acc_money' },
              key: 'prop_acc_money_rel',
              name: isAr ? 'حركات الأموال' : 'Money Movements',
              type: 'relation',
            },
          ],
          title: isAr ? 'الحسابات والخزائن' : 'Accounts',
          views: [{ key: 'view_accounts_all', layout: 'table', name: isAr ? 'كل الحسابات' : 'All Accounts', propertyKeys: ['prop_acc_name', 'prop_acc_type', 'prop_acc_balance'], sorts: [{ direction: 'asc', propertyId: 'prop_acc_name' }] }],
          visibility: 'normal',
        },
        {
          key: 'db_transactions',
          properties: [
            { key: 'prop_tx_no', name: isAr ? 'رقم المعاملة' : 'Transaction #', required: true, type: 'title' },
            {
              key: 'prop_tx_type',
              name: isAr ? 'النوع' : 'Type',
              options: [
                { label: isAr ? 'بيع' : 'Sale' },
                { label: isAr ? 'شراء' : 'Purchase' },
                { label: isAr ? 'مصروف' : 'Expense' },
                { label: isAr ? 'تحويل' : 'Transfer' },
                { label: isAr ? 'دخل' : 'Income' },
                { label: isAr ? 'تسوية' : 'Adjustment' },
                { label: isAr ? 'عكس' : 'Reversal' },
              ],
              type: 'select',
            },
            { key: 'prop_tx_date', name: isAr ? 'التاريخ' : 'Date', type: 'date' },
            { key: 'prop_tx_quantity', name: isAr ? 'الكمية' : 'Quantity', type: 'number' },
            { key: 'prop_tx_unit_price', name: isAr ? 'سعر الوحدة' : 'Unit Price', type: 'number' },
            {
              config: { formula: { expression: '[prop_tx_quantity] * [prop_tx_unit_price]' } },
              key: 'prop_tx_line_total',
              name: isAr ? 'إجمالي الكمية × السعر' : 'Quantity × Price',
              type: 'formula',
            },
            { key: 'prop_tx_amount', name: isAr ? 'المبلغ الإجمالي' : 'Total Amount', type: 'number' },
            { key: 'prop_tx_fee', name: isAr ? 'الرسوم' : 'Total Fee', type: 'number' },
            { key: 'prop_tx_net', name: isAr ? 'الصافي' : 'Net Amount', type: 'number' },
            {
              key: 'prop_tx_payment_method',
              name: isAr ? 'طريقة الدفع' : 'Payment Method',
              options: [
                { label: isAr ? 'نقدي' : 'Cash' }, { label: 'Vodafone Cash' }, { label: 'e& Cash' },
                { label: 'Aman' }, { label: 'InstaPay' }, { label: isAr ? 'بطاقة' : 'Card' },
                { label: isAr ? 'تحويل بنكي' : 'Bank Transfer' }, { label: isAr ? 'آجل' : 'Credit' },
              ],
              type: 'select',
            },
            { config: { relationId: 'rel_tx_product' }, key: 'prop_tx_product_rel', name: isAr ? 'الصنف' : 'Item', type: 'relation' },
            {
              config: { relationId: 'rel_tx_person' },
              key: 'prop_tx_person_rel',
              name: isAr ? 'العميل / المورد' : 'Person',
              type: 'relation',
            },
            {
              config: { relationId: 'rel_tx_account' },
              key: 'prop_tx_acc_rel',
              name: isAr ? 'الحساب' : 'Account',
              type: 'relation',
            },
          ],
          title: isAr ? 'المعاملات والفواتير' : 'Transactions',
          defaultViewKey: 'view_tx_today',
          views: [
            {
              filterAst: { kind: 'property', operator: 'relative_date', propertyId: 'prop_tx_date', relativePeriod: 'TODAY' },
              group: { dateGranularity: 'day', propertyId: 'prop_tx_date' },
              key: 'view_tx_today', layout: 'table',
              layoutConfig: { calculations: [{ calculation: 'sum', propertyId: 'prop_tx_amount' }, { calculation: 'sum', propertyId: 'prop_tx_fee' }, { calculation: 'sum', propertyId: 'prop_tx_net' }] },
              name: isAr ? 'اليوم' : 'Today',
              propertyKeys: ['prop_tx_no', 'prop_tx_date', 'prop_tx_product_rel', 'prop_tx_quantity', 'prop_tx_unit_price', 'prop_tx_amount', 'prop_tx_payment_method', 'prop_tx_fee', 'prop_tx_net'],
              sorts: [{ direction: 'desc', propertyId: 'prop_tx_date' }],
            },
            {
              filterAst: { kind: 'property', operator: 'relative_date', propertyId: 'prop_tx_date', relativePeriod: 'THIS_WEEK' },
              group: { dateGranularity: 'day', propertyId: 'prop_tx_date' }, key: 'view_tx_week', layout: 'table',
              layoutConfig: { calculations: [{ calculation: 'sum', propertyId: 'prop_tx_amount' }, { calculation: 'sum', propertyId: 'prop_tx_fee' }, { calculation: 'sum', propertyId: 'prop_tx_net' }] },
              name: isAr ? 'هذا الأسبوع' : 'This Week', sorts: [{ direction: 'desc', propertyId: 'prop_tx_date' }],
            },
            {
              filterAst: { kind: 'property', operator: 'relative_date', propertyId: 'prop_tx_date', relativePeriod: 'THIS_MONTH' },
              group: { dateGranularity: 'week', propertyId: 'prop_tx_date' }, key: 'view_tx_month', layout: 'table',
              layoutConfig: { calculations: [{ calculation: 'sum', propertyId: 'prop_tx_amount' }, { calculation: 'sum', propertyId: 'prop_tx_fee' }, { calculation: 'sum', propertyId: 'prop_tx_net' }] },
              name: isAr ? 'هذا الشهر' : 'This Month', sorts: [{ direction: 'desc', propertyId: 'prop_tx_date' }],
            },
            { group: { dateGranularity: 'month', propertyId: 'prop_tx_date' }, key: 'view_tx_all', layout: 'table', name: isAr ? 'كل المعاملات' : 'All Transactions', sorts: [{ direction: 'desc', propertyId: 'prop_tx_date' }] },
          ],
          visibility: 'normal',
        },
        {
          key: 'db_inventory_movements',
          properties: [
            { key: 'prop_inv_title', name: isAr ? 'الوصف' : 'Description', required: true, type: 'title' },
            { key: 'prop_inv_date', name: isAr ? 'التاريخ' : 'Date', type: 'date' },
            { key: 'prop_inv_delta', name: isAr ? 'فرق الكمية' : 'Quantity Delta', type: 'number' },
            {
              config: { relationId: 'rel_prod_inv' },
              key: 'prop_inv_prod_rel',
              name: isAr ? 'المنتج' : 'Product',
              type: 'relation',
            },
            {
              config: { relationId: 'rel_tx_inv' },
              key: 'prop_inv_tx_rel',
              name: isAr ? 'المعاملة' : 'Transaction',
              type: 'relation',
            },
          ],
          title: isAr ? 'حركات المخزون التفصيلية' : 'Inventory Movements',
          views: [{ group: { dateGranularity: 'day', propertyId: 'prop_inv_date' }, key: 'view_inv_all', layout: 'table', name: isAr ? 'كل حركات المخزون' : 'All Inventory Movements', sorts: [{ direction: 'desc', propertyId: 'prop_inv_date' }] }],
          visibility: 'advanced',
        },
        {
          key: 'db_money_movements',
          properties: [
            { key: 'prop_mm_title', name: isAr ? 'الوصف' : 'Description', required: true, type: 'title' },
            { key: 'prop_mm_date', name: isAr ? 'التاريخ' : 'Date', type: 'date' },
            { key: 'prop_mm_amount', name: isAr ? 'المبلغ' : 'Amount', type: 'number' },
            {
              config: { relationId: 'rel_acc_money' },
              key: 'prop_mm_acc_rel',
              name: isAr ? 'الحساب' : 'Account',
              type: 'relation',
            },
            {
              config: { relationId: 'rel_people_money' },
              key: 'prop_mm_person_rel',
              name: isAr ? 'جهة التعامل' : 'Person',
              type: 'relation',
            },
            {
              config: { relationId: 'rel_tx_money' },
              key: 'prop_mm_tx_rel',
              name: isAr ? 'المعاملة' : 'Transaction',
              type: 'relation',
            },
          ],
          title: isAr ? 'حركات الأموال التفصيلية' : 'Money Movements',
          views: [{ group: { dateGranularity: 'day', propertyId: 'prop_mm_date' }, key: 'view_money_all', layout: 'table', layoutConfig: { calculations: [{ calculation: 'sum', propertyId: 'prop_mm_amount' }] }, name: isAr ? 'كل حركات الأموال' : 'All Money Movements', sorts: [{ direction: 'desc', propertyId: 'prop_mm_date' }] }],
          visibility: 'advanced',
        },
      ],
      description: isAr ? 'مساحة عمل جاهزة لإدارة المحلات التجارية والمخزون والحسابات' : 'Ready-to-use retail workspace template for shop operations, inventory, and accounts.',
      name: isAr ? 'متجر الهواتف' : 'Phone Shop',
      pages: [
        { contentJson: JSON.stringify([{ calloutIcon: '📅', content: isAr ? 'المبيعات والرسوم وصافي اليوم محسوبة من قاعدة البيانات.' : 'Today’s sales, fees, and net totals are calculated from the database.', id: 'phone_daily_note', type: 'callout' }, { content: '', databaseId: 'db_transactions', id: 'phone_daily_db', type: 'database-view', viewId: 'view_tx_today' }]), icon: 'lucide:ClipboardCheck', key: 'page_daily', title: isAr ? 'تشغيل اليوم' : 'Daily Operations' },
        { contentJson: JSON.stringify([{ content: '', databaseId: 'db_products', id: 'phone_inventory_db', type: 'database-view', viewId: 'view_products_all' }]), icon: 'lucide:Boxes', key: 'page_inventory', title: isAr ? 'المخزون' : 'Inventory' },
        { contentJson: JSON.stringify([{ content: '', databaseId: 'db_people', id: 'phone_people_db', type: 'database-view', viewId: 'view_people_all' }]), icon: 'lucide:Users', key: 'page_people', title: isAr ? 'الأشخاص والحسابات' : 'People & Accounts' },
      ],
      recordTemplates: [
        { contentJson: JSON.stringify([{ content: isAr ? 'بيانات الجهاز والضمان والملحقات.' : 'Device details, warranty, and included accessories.', id: 'device_notes', type: 'callout' }]), databaseKey: 'db_products', defaults: { prop_prod_active: true }, icon: '📱', key: 'record_device', name: isAr ? 'جهاز' : 'Device' },
        { databaseKey: 'db_products', defaults: { prop_prod_active: true }, icon: '🎧', key: 'record_accessory', name: isAr ? 'إكسسوار' : 'Accessory' },
        { databaseKey: 'db_people', icon: '👤', key: 'record_customer', name: isAr ? 'عميل' : 'Customer' },
        { databaseKey: 'db_people', icon: '🚚', key: 'record_supplier', name: isAr ? 'مورد' : 'Supplier' },
        { databaseKey: 'db_accounts', icon: '💵', key: 'record_cash_account', name: isAr ? 'حساب نقدي' : 'Cash Account' },
        { databaseKey: 'db_accounts', icon: '📲', key: 'record_wallet_account', name: isAr ? 'محفظة رقمية' : 'Digital Wallet' },
        { databaseKey: 'db_transactions', icon: '🧾', key: 'record_sale', name: isAr ? 'عملية بيع' : 'Sale' },
      ],
      relations: [
        {
          inversePropertyKey: 'prop_inv_prod_rel',
          key: 'rel_prod_inv',
          sourceCardinality: 'one',
          sourceDatabaseKey: 'db_products',
          sourcePropertyKey: 'prop_prod_inv_rel',
          targetCardinality: 'many',
          targetDatabaseKey: 'db_inventory_movements',
        },
        {
          inversePropertyKey: 'prop_mm_person_rel',
          key: 'rel_people_money',
          sourceCardinality: 'one',
          sourceDatabaseKey: 'db_people',
          sourcePropertyKey: 'prop_people_money_rel',
          targetCardinality: 'many',
          targetDatabaseKey: 'db_money_movements',
        },
        {
          inversePropertyKey: 'prop_mm_acc_rel',
          key: 'rel_acc_money',
          sourceCardinality: 'one',
          sourceDatabaseKey: 'db_accounts',
          sourcePropertyKey: 'prop_acc_money_rel',
          targetCardinality: 'many',
          targetDatabaseKey: 'db_money_movements',
        },
        {
          inversePropertyName: isAr ? 'المعاملات' : 'Transactions',
          key: 'rel_tx_person',
          sourceCardinality: 'many',
          sourceDatabaseKey: 'db_transactions',
          sourcePropertyKey: 'prop_tx_person_rel',
          targetCardinality: 'one',
          targetDatabaseKey: 'db_people',
        },
        {
          inversePropertyName: isAr ? 'المعاملات' : 'Transactions',
          key: 'rel_tx_account',
          sourceCardinality: 'many',
          sourceDatabaseKey: 'db_transactions',
          sourcePropertyKey: 'prop_tx_acc_rel',
          targetCardinality: 'one',
          targetDatabaseKey: 'db_accounts',
        },
        {
          inversePropertyName: isAr ? 'المبيعات' : 'Sales', key: 'rel_tx_product', sourceCardinality: 'many',
          sourceDatabaseKey: 'db_transactions', sourcePropertyKey: 'prop_tx_product_rel', targetCardinality: 'one', targetDatabaseKey: 'db_products',
        },
        {
          inversePropertyName: isAr ? 'حركات المخزون' : 'Inventory Movements',
          key: 'rel_tx_inv',
          sourceCardinality: 'many',
          sourceDatabaseKey: 'db_inventory_movements',
          sourcePropertyKey: 'prop_inv_tx_rel',
          targetCardinality: 'one',
          targetDatabaseKey: 'db_transactions',
        },
        {
          inversePropertyName: isAr ? 'حركات الأموال' : 'Money Movements',
          key: 'rel_tx_money',
          sourceCardinality: 'many',
          sourceDatabaseKey: 'db_money_movements',
          sourcePropertyKey: 'prop_mm_tx_rel',
          targetCardinality: 'one',
          targetDatabaseKey: 'db_transactions',
        },
      ],
      version: 2,
      workflows: [],
    };
}
